// Empty wrapper.  This dummy file is renamed  e.g. 'FPRelease.ipf'  or 'FPTest.ipf'  and distributed in the Release version.  
// This is a workaround needed because Igor insists on a file with that name. Conditional compilation would be a far more elegant solution...                            
